version: '3.3'
services:
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: 123456Ab
      # Password for root access
      MYSQL_ROOT_PASSWORD: 428329Ae
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - ./db_data:/usr/data
    container_name: mysql_db
# Names our volume
volumes:
  my-db: